<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anatoly-Korzuns-MacBook-Pro.local" name="Test" tests="12" failures="11" timestamp="3 Aug 2012 09:48:39 GMT" time="3637.718" errors="0">
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command close could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command close could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.close(DefaultSelenium.java:427)
	at com.example.tests.SeleniumHelper.dismissSelenium(SeleniumHelper.java:77)
	at com.example.tests.TestBase.tearDown(TestBase.java:26)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="testStep1" time="10.938" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Element css=div.content_body_header not found">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element css=div.content_body_header not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:275)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getString(LoggingCommandProcessor.java:238)
	at com.thoughtworks.selenium.DefaultSelenium.getText(DefaultSelenium.java:471)
	at com.example.tests.Step1.testStep1(Step1.java:14)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1Find" time="20.578" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Element css=div.content_body_header not found">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element css=div.content_body_header not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:275)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getString(LoggingCommandProcessor.java:238)
	at com.thoughtworks.selenium.DefaultSelenium.getText(DefaultSelenium.java:471)
	at com.example.tests.Step1.testStep1Find(Step1.java:43)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1Find -->
  <testcase name="testStep1Find" time="7.264" classname="com.example.tests.Step1">
    <failure type="java.lang.RuntimeException" message="result was neither &amp;apos;true&amp;apos; nor &amp;apos;false&amp;apos;: ">
      <![CDATA[java.lang.RuntimeException: result was neither 'true' nor 'false': 
	at com.thoughtworks.selenium.HttpCommandProcessor.getBoolean(HttpCommandProcessor.java:358)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getBoolean(LoggingCommandProcessor.java:168)
	at com.thoughtworks.selenium.DefaultSelenium.isAlertPresent(DefaultSelenium.java:431)
	at com.example.tests.Step1.testStep1Find(Step1.java:36)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1Find -->
  <testcase name="testStep1Find" time="0.393" classname="com.example.tests.Step1">
    <failure type="java.lang.RuntimeException" message="result was neither &amp;apos;true&amp;apos; nor &amp;apos;false&amp;apos;: Выбор номера">
      <![CDATA[java.lang.RuntimeException: result was neither 'true' nor 'false': Выбор номера
	at com.thoughtworks.selenium.HttpCommandProcessor.getBoolean(HttpCommandProcessor.java:358)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getBoolean(LoggingCommandProcessor.java:168)
	at com.thoughtworks.selenium.DefaultSelenium.isAlertPresent(DefaultSelenium.java:431)
	at com.example.tests.Step1.testStep1Find(Step1.java:36)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1Find -->
  <testcase name="testStep2" time="57.243" classname="com.example.tests.Step2">
    <failure type="java.lang.AssertionError" message="timeout">
      <![CDATA[java.lang.AssertionError: timeout
	at com.example.tests.Step2.testStep2(Step2.java:121)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testStep2 -->
  <testcase name="testStep2" time="16.879" classname="com.example.tests.Step2"/>
  <testcase name="testStep1" time="1817.363" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Command timed out">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Command timed out
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:275)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getString(LoggingCommandProcessor.java:238)
	at com.thoughtworks.selenium.DefaultSelenium.getText(DefaultSelenium.java:471)
	at com.example.tests.Step1.testStep1(Step1.java:14)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="1800.439" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Command timed out">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Command timed out
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.example.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="0.426" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.example.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="0.428" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.example.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="0.428" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.example.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="0.437" classname="com.example.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.example.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
</testsuite> <!-- Test -->
